layout_spectrum: 0.2616487
typography_spectrum: 1
color:
  saturation: 0.8561081
  lightness: 0.3121409
  brandStrength: 0.3059396
  rhythmicContrast: 0.9503418
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: "Michael Angelo's Winery"
